### ISSUE TITLE
typo in bid wars

### ISSUE THREAD

**Issue by florczakraf** [GramyPomagamy/gsps-layouts#92]
`Wpłać jako pierwszy na tą licytację` -> `Wpłać jako pierwszy na tę licytację`

**Comment by kawalekw** [comment]
https://github.com/GramyPomagamy/gsps-layouts/blob/f6c43ca6de025ed2feaec67b00973e1897b6aebd/src/browser/graphics/components/omnibar/ticker/bids.tsx#L237
